import jsPDF from 'jspdf';

interface SimpleRateCardData {
  creatorName: string;
  handle?: string;
  platform: string;
  followers: number;
  engagementRate: number;
  niche: string;
  singlePostRate: number;
}

function formatNumber(num: number): string {
  if (num >= 1000000) {
    return `${(num / 1000000).toFixed(1)}M`;
  }

  if (num >= 1000) {
    return `${(num / 1000).toFixed(1)}K`;
  }

  return `${num}`;
}

export function generateSimpleRateCard(data: SimpleRateCardData): void {
  const doc = new jsPDF();

  doc.setFillColor(255, 255, 255);
  doc.rect(0, 0, 210, 297, 'F');

  doc.setFillColor(99, 102, 241);
  doc.rect(0, 0, 210, 50, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(28);
  doc.setFont('helvetica', 'bold');
  doc.text(data.creatorName, 105, 25, { align: 'center' });

  if (data.handle) {
    doc.setFontSize(13);
    doc.setFont('helvetica', 'normal');
    doc.text(data.handle, 105, 35, { align: 'center' });
  }

  doc.setFontSize(11);
  doc.text(`${data.platform} Creator`, 105, 43, { align: 'center' });

  const statsY = 70;
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text('Followers', 40, statsY);
  doc.text('Engagement', 105, statsY, { align: 'center' });
  doc.text('Niche', 170, statsY, { align: 'right' });

  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(99, 102, 241);
  doc.text(formatNumber(data.followers), 40, statsY + 12);
  doc.text(`${data.engagementRate}%`, 105, statsY + 12, { align: 'center' });
  doc.text(data.niche, 170, statsY + 12, { align: 'right' });

  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.5);
  doc.line(20, statsY + 25, 190, statsY + 25);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Standard Rate', 105, 115, { align: 'center' });

  doc.setFillColor(248, 250, 252);
  doc.roundedRect(50, 125, 110, 40, 5, 5, 'F');

  doc.setFontSize(36);
  doc.setTextColor(99, 102, 241);
  doc.text(`$${data.singlePostRate.toLocaleString()}`, 105, 150, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.setFont('helvetica', 'normal');
  doc.text('per post', 105, 160, { align: 'center' });

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text("What's Included:", 20, 185);

  doc.setFontSize(11);
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  const includes = [
    'One post on my feed',
    'Professional content creation',
    'Brand mention and tags',
    '30-day usage rights',
  ];

  includes.forEach((item, index) => {
    doc.text(`- ${item}`, 25, 195 + index * 8);
  });

  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont('helvetica', 'bold');
  doc.text('Standard Terms:', 20, 235);

  doc.setFontSize(9);
  doc.setTextColor(80, 80, 80);
  doc.setFont('helvetica', 'normal');
  const terms = [
    'Payment: 50% upfront, 50% upon content delivery',
    'Timeline: 7-10 business days from brief',
    'Revisions: Up to 2 rounds included',
    'Usage: 30-day organic posting rights included',
  ];

  terms.forEach((term, index) => {
    doc.text(`- ${term}`, 20, 245 + index * 6);
  });

  doc.setFillColor(248, 250, 252);
  doc.rect(0, 273, 210, 24, 'F');

  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text('Generated by RateRight', 105, 283, { align: 'center' });
  doc.text(new Date().toLocaleDateString(), 105, 289, { align: 'center' });

  doc.setTextColor(200, 200, 200);
  doc.setFontSize(7);
  doc.text('Free Plan - Upgrade for Premium Templates', 105, 294, { align: 'center' });

  const filename = `${data.creatorName.replace(/\s/g, '_')}_Rate_Card.pdf`;
  doc.save(filename);
}
